apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: upbound-function-cidr
  annotations:
    render.crossplane.io/runtime: Development
# spec:
#   package: xpkg.upbound.io/upbound/function-cidr:v0.3.0
