apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xcidrs.platform.upbound.io
spec:
  group: platform.upbound.io
  names:
    kind: XCIDR
    plural: xcidrs
  claimNames:
    kind: CIDR
    plural: cidrs
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  description: CIDR Input parameters
                  type: object
                  properties:
                    cidrFunc:
                      type: string
                      enum:
                        - cidrsubnet
                        - cidrsubnets
                        - cidrhost
                        - cidrnetmask
                        - cidrsubnetloop
                    cidrBlock:
                      type: string
                    newBits:
                      type: array
                      items:
                        type: integer
                    azs:
                      type: array
                      items:
                        type: string
                    hostNum:
                      type: integer
                    offset:
                      type: integer
                    output:
                      type: string
              required:
                - parameters
            status:
              description: Representing observed state.
              properties:
                cidr:
                  description: CIDR observed status.
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
